name:                wolfram
version:             0.1.0.0
author:              "Alexis CHERON"
copyright:           "2022 Alexis CHERON"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  wolfram-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wolfram

tests:
  wolfram-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wolfram
